# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_id=sootychimneys
mod_version=1.3.4
mod_release_type=release
mod_name=Sooty Chimneys
mod_description=Spiritual successor to campfires!
archives_name=sootychimneys
maven_group=io.github.mortuusars.sootychimneys
mod_license=MIT
mod_authors=mortuusars
mod_page=https://www.curseforge.com/minecraft/mc-mods/sooty-chimneys
mod_github=https://github.com/mortuusars/sootychimneys
mod_issues=https://github.com/mortuusars/sootychimneys/issues
enabled_platforms=fabric,neoforge
mod_curseforge_project_id=634005
mod_modrinth_project_id=b3w1XM9H
# Minecraft properties
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)
supported_minecraft_versions=1.21.11
parchment_version=1.21.10:2025.10.12
# Fabric
fabric_loader_version=0.18.1
fabric_api_version=0.139.5+1.21.11
# NeoForge
neoforge_version=21.11.24-beta
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)
# Dependencies
forge_config_api_port_version=21.11.0
mixinextras_version=0.4.1
# Mod Versions
jei_version=27.4.0.15
jade_version=20.0.5

