# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_id=sootychimneys
mod_version=1.3.4
mod_release_type=release
mod_name=Sooty Chimneys
mod_description=Spiritual successor to campfires!
archives_name=sootychimneys
maven_group=io.github.mortuusars.sootychimneys
mod_license=MIT
mod_authors=mortuusars
mod_page=https://www.curseforge.com/minecraft/mc-mods/sooty-chimneys
mod_github=https://github.com/mortuusars/sootychimneys
mod_issues=https://github.com/mortuusars/sootychimneys/issues
enabled_platforms=fabric,neoforge
mod_curseforge_project_id=634005
mod_modrinth_project_id=b3w1XM9H
# Minecraft properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,)
supported_minecraft_versions=1.21,1.21.1
parchment_version=1.21.1:2024.11.17
# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.102.1+1.21.1
# NeoForge
neoforge_version=21.1.129
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)
# Mod Dependencies
forge_config_api_port_version=21.1.0
jei_version=19.19.0.220
# Create
create_version=6.0.3-47
ponder_version=1.0.45
flywheel_version=1.0.1
registrate_version=MC1.21-1.3.0+62

