architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}

configurations {
    create("junit")
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    api "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api_port_version}"
    compileOnlyApi "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"

    testImplementation(platform("org.junit:junit-bom:${project.property("jupiterVersion")}"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    "junit"(platform("org.junit:junit-bom:${project.property("jupiterVersion")}"))
    "junit"("org.junit.jupiter:junit-jupiter")
}

tasks {
    test {
        useJUnitPlatform()
    }
}

// Makes datagenerated resources usable:
sourceSets {
    main {
        // We are using NeoForge to datagen, and it outputs to the 'common/src/generated' folder
        resources.srcDir file("src/generated")
    }
}
